apiVersion: apps.nvidia.com/v1alpha1
kind: NemoAgentConfig
metadata:
  name: nemo-agent-config
  namespace: nemo
spec:
  functions:
    wikipedia_search:
      _type: wiki_search
      max_results: 2
  llms:
    nim_llm:
      _type: nim
      model_name: nvidia/nemotron-3-nano
      base_url: http://llama-3-1-70b-instruct:8000/v1
      temperature: 0.0
      chat_template_kwargs:
        enable_thinking: false
  workflow:
    _type: react_agent
    tool_names:
    - wikipedia_search
    llm_name: nim_llm
    verbose: true
    parse_agent_response_max_retries: 3
  pod:
    name: sleep-pod-1
    containerName: curl
    restartPolicy: Never
    configMount:
      name: cm-storage
      mountPath: /model-store
      key: config.yml
      path: workflow.yml
    image:
      repository: localhost:5000/nvstaging/nvidia-nat
      tag: "v1.6.0"
      pullPolicy: Always
    command:
    - sleep
    args:
    - "360000"
