/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/NVIDIA/k8s-nim-operator/api/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNemoAgentConfigs implements NemoAgentConfigInterface
type FakeNemoAgentConfigs struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var nemoagentconfigsResource = v1alpha1.SchemeGroupVersion.WithResource("nemoagentconfigs")

var nemoagentconfigsKind = v1alpha1.SchemeGroupVersion.WithKind("NemoAgentConfig")

// Get takes name of the nemoAgentConfig, and returns the corresponding nemoAgentConfig object, and an error if there is any.
func (c *FakeNemoAgentConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NemoAgentConfig, err error) {
	emptyResult := &v1alpha1.NemoAgentConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(nemoagentconfigsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoAgentConfig), err
}

// List takes label and field selectors, and returns the list of NemoAgentConfigs that match those selectors.
func (c *FakeNemoAgentConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NemoAgentConfigList, err error) {
	emptyResult := &v1alpha1.NemoAgentConfigList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(nemoagentconfigsResource, nemoagentconfigsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NemoAgentConfigList{ListMeta: obj.(*v1alpha1.NemoAgentConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.NemoAgentConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nemoAgentConfigs.
func (c *FakeNemoAgentConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(nemoagentconfigsResource, c.ns, opts))

}

// Create takes the representation of a nemoAgentConfig and creates it.  Returns the server's representation of the nemoAgentConfig, and an error, if there is any.
func (c *FakeNemoAgentConfigs) Create(ctx context.Context, nemoAgentConfig *v1alpha1.NemoAgentConfig, opts v1.CreateOptions) (result *v1alpha1.NemoAgentConfig, err error) {
	emptyResult := &v1alpha1.NemoAgentConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(nemoagentconfigsResource, c.ns, nemoAgentConfig, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoAgentConfig), err
}

// Update takes the representation of a nemoAgentConfig and updates it. Returns the server's representation of the nemoAgentConfig, and an error, if there is any.
func (c *FakeNemoAgentConfigs) Update(ctx context.Context, nemoAgentConfig *v1alpha1.NemoAgentConfig, opts v1.UpdateOptions) (result *v1alpha1.NemoAgentConfig, err error) {
	emptyResult := &v1alpha1.NemoAgentConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(nemoagentconfigsResource, c.ns, nemoAgentConfig, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoAgentConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNemoAgentConfigs) UpdateStatus(ctx context.Context, nemoAgentConfig *v1alpha1.NemoAgentConfig, opts v1.UpdateOptions) (result *v1alpha1.NemoAgentConfig, err error) {
	emptyResult := &v1alpha1.NemoAgentConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(nemoagentconfigsResource, "status", c.ns, nemoAgentConfig, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoAgentConfig), err
}

// Delete takes name of the nemoAgentConfig and deletes it. Returns an error if one occurs.
func (c *FakeNemoAgentConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nemoagentconfigsResource, c.ns, name, opts), &v1alpha1.NemoAgentConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNemoAgentConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(nemoagentconfigsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NemoAgentConfigList{})
	return err
}

// Patch applies the patch and returns the patched nemoAgentConfig.
func (c *FakeNemoAgentConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NemoAgentConfig, err error) {
	emptyResult := &v1alpha1.NemoAgentConfig{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(nemoagentconfigsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.NemoAgentConfig), err
}
